const fs=require('fs'); const path=require('path'); const crypto=require('crypto'); const {append}=require('../functions/logs'); const {storageError}=require('./errors');
const ROOT=path.join(process.cwd(),'secrets','storage_signing');
const b64=(b)=>Buffer.from(b).toString('base64url');
function ensureSecret(projectId){fs.mkdirSync(ROOT,{recursive:true}); const f=path.join(ROOT,`${projectId}.json`); if(!fs.existsSync(f)) fs.writeFileSync(f,JSON.stringify({secret:crypto.randomBytes(32).toString('hex')},null,2)); return JSON.parse(fs.readFileSync(f,'utf8')).secret;}
function canonical(q){return ['projectId','bucket','key','exp','method','contentType','contentLength','signedUid'].map(k=>`${k}=${q[k]||''}`).join('\n');}
function sign(projectId,p){return b64(crypto.createHmac('sha256',ensureSecret(projectId)).update(canonical(p)).digest());}
function issue(projectId,payload){const exp=Math.floor(Date.now()/1000)+(payload.expSeconds||300); const base={projectId,bucket:payload.bucket,key:payload.key,exp,method:payload.method,contentType:payload.contentType||'',contentLength:payload.contentLength||'',signedUid:payload.signedUid||''}; const sig=sign(projectId,base); append({projectId,type:'storage.signed_url.issued',bucket:payload.bucket,key:payload.key,method:payload.method}); return `/v1/storage/object?projectId=${encodeURIComponent(projectId)}&bucket=${encodeURIComponent(payload.bucket)}&key=${encodeURIComponent(payload.key)}&exp=${exp}&method=${payload.method}&contentType=${encodeURIComponent(base.contentType)}&contentLength=${base.contentLength}&signedUid=${encodeURIComponent(base.signedUid)}&sig=${encodeURIComponent(sig)}`;}
function verify(q,method,headers={}){if(Number(q.exp)<Math.floor(Date.now()/1000)) throw storageError('SIGNED_URL_EXPIRED','Signed URL expired'); if(String(q.method).toUpperCase()!==String(method).toUpperCase()) throw storageError('SIGNED_URL_METHOD','Method mismatch'); if(sign(q.projectId,q)!==q.sig) throw storageError('SIGNED_URL_INVALID','Bad signature'); if(q.contentType&&headers['content-type']&&q.contentType!==headers['content-type']) throw storageError('CONTENT_TYPE_MISMATCH','Content type mismatch'); if(q.contentLength&&headers['content-length']&&Number(q.contentLength)!==Number(headers['content-length'])) throw storageError('CONTENT_LENGTH_MISMATCH','Content length mismatch');}
module.exports={issue,verify,canonical};
